var major = {
	"Agriculture, Agriculture Operations, and Related Sciences": "Agriculture, Agriculture Operations, and Related Sciences",
	"Architecture and Related Sciences": "Architecture and Related Sciences",
	"Area, Ethnic, Cultural, Gender, and Group Studies": "Area, Ethnic, Cultural, Gender, and Group Studies",
	"Basic Skills and Developmental/Remedial Education": "Basic Skills and Developmental/Remedial Education",
	"Biological and Biomedical Sciences": "Biological and Biomedical Sciences",
	"Business, Management, Marketing, and Related Support Services": "Business, Management, Marketing, and Related Support Services",
	"Citizenship Activities": "Citizenship Activities",
	"Communication, Journalism, and Related Programs": "Communication, Journalism, and Related Programs",
	"Communication Technologies/Technicians and Support Services": "Communication Technologies/Technicians and Support Services",
	"Computer and Information Sciences and Support Services": "Computer and Information Sciences and Support Services",
	"Construction Tools": "Construction Tools",
	"Education": "Education",
	"Engineering": "Engineering",
	"Engineering Technologies and Engineering-Related Fields": "Engineering Technologies and Engineering-Related Fields",
	"English Language and Literature/Letters": "English Language and Literature/Letters",
	"Foreign Languages, Literatures, and Linguistics": "Foreign Languages, Literatures, and Linguistics",
	"Family and Consumer Sciences/Human Sciences": "Family and Consumer Sciences/Human Sciences",
	"Health Professions and Related Programs": "Health Professions and Related Programs",
	"Health-Related Knowledge and Skills": "Health-Related Knowledge and Skills",
	"High School/Secondary Diplomas and Certificates": "High School/Secondary Diplomas and Certificates",
	"History": "History",
	"Homeland Security, Law Enforcement, Firefighting and Related Protective Services": "Homeland Security, Law Enforcement, Firefighting and Related Protective Services",
	"Interpersonal and Social Skills": "Interpersonal and Social Skills",
	"Legal Professions and Studies": "Legal Professions and Studies",
	"Leisure and Recreational Activities": "Leisure and Recreational Activities",
	"Liberal Arts and Sciences, General Studies and Humanities": "Liberal Arts and Sciences, General Studies and Humanities",
	"Library Science": "Library Science",
	"Mathematics and Statistics": "Mathematics and Statistics",
	"Mechanic and Repair Technologies/Technicians": "Mechanic and Repair Technologies/Technicians",
	"Military Science, Leadership and Operational Art": "Military Science, Leadership and Operational Art",
	"Military Technologies and Applied Sciences": "Military Technologies and Applied Sciences",
	"Multi/Interdisciplinary Studies": "Multi/Interdisciplinary Studies",
	"Parks, Recreation, Leisure, and Fitness Studies": "Parks, Recreation, Leisure, and Fitness Studies",
	"Personal Awareness and Self-Improvement": "Personal Awareness and Self-Improvement",
	"Philosophy and Religious Studies": "Philosophy and Religious Studies",
	"Physical Sciences": "Physical Sciences",
	"Precision Production": "Precision Production",
	"Psychology": "Psychology",
	"Public Administration and Social Service Professions": "Public Administration and Social Service Professions",
	"Residency Programs": "Residency Programs",
	"Science Technologies/Technicians": "Science Technologies/Technicians",
	"Social Sciences": "Social Sciences",
	"Technology Education/Industrial Arts": "Technology Education/Industrial Arts",
	"Theology and Religious Vocations": "Theology and Religious Vocations",
	"Transportation and Materials Moving": "Transportation and Materials Moving",
	"Visual and Performing Arts": "Visual and Performing Arts"
	
	
};